#!/bin/sh
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

echo "GITFLOW_VERSION=$1" > git-flow-version
git add git-flow-version
git commit -m "Bumped version number to $1" git-flow-version
