#!/bin/sh

usage() {
	echo "usage: gitflow start hotfix <release>"
	echo "       gitflow finish hotfix <release>"
}

start() {
	# TODO
	gitflow_check_clean_working_tree
	echo "git checkout -b hotfix-$RELEASE master"
	echo "Bump version number"
	echo "Fix bug"
}

finish() {
	# TODO
	gitflow_check_clean_working_tree
	echo "git checkout master"
	echo "git merge --no-ff hotfix-$RELEASE"
	echo "git checkout develop"
	echo "git merge --no-ff hotfix-$RELEASE"
	echo "git branch -d hotfix-$RELEASE"
}

