#!/bin/sh
#
# Runs at the end of git flow feature start
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
# $4    The base from which this feature is started
#
NAME=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

# Implement your script here.

exit 0
