#!/bin/sh
#
# Ran before git flow feature pull.
#
# Positional arguments:
# $1    The friendly name of the branch
# $2    The remote to pull from
# $3    The full branch name (including the feature prefix)
#
NAME=$1
REMOTE=$2
BRANCH=$3

# Implement your script here.
# To terminate the git-flow action, return a non-zero exit code.
exit 0
