#!/bin/sh
#
# Runs before git flow release finish
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
#
VERSION=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.

# To terminate the git-flow action, return a non-zero exit code.
exit 0
